### ISSUE TITLE
Feature suggestion for mkvtomp4: add external subtitles

### ISSUE THREAD

**Issue by morberg** [mshick/arrivals-osx#1]
(Issues can't be added to your branch of mkvtomp4 where this issue should be, perhaps they are [turned off](https://help.github.com/articles/disabling-issues/)?)

It would be useful to add an option to add an external subtitle file to the final mp4 file. Say you have two files: `video.mkv`and  `subtitle.en.srt`. I would like to combine these and end up with a `video.mp4` which has `subtitle.en.srt` embedded as a tx3g text track.

With ffmpeg you can add an external subtitle track (I've only used this once and not tested it extensively) to an .mp4 file using:

```
ffmpeg -i video.mp4 -i subtitle.en.srt -c:v copy -c:a copy -c:s mov_text out.mp4
```

According to [this stackoverflow page](http://stackoverflow.com/questions/8979288/adding-subtitle-from-command-line-mp4box) you should be able to add the following option to MP4Box:

```
-add "subtitle.en.srt":lang=eng:layout=0x60x0x-1:group=2:hdlr="sbtl:tx3g"
```

I have no idea how to best implement it, just a couple of thoughts to get things started.

**Comment by mshick** [comment]
Yeah, maybe I need to properly branch that repo, rather than just the fork. There hasn't been any active work on the main project, so thinking it might be dead.
